export const producers = [
    { value: "Aniplex", label: "Aniplex" },
    { value: "Dentsu", label: "Dentsu" },
    { value: "Shueisha Productions", label: "Shueisha Productions" },
    { value: "Crunchyroll", label: "Crunchyroll" },
    { value: "Kadokawa", label: "Kadokawa" },
    { value: "Bandai Namco Arts", label: "Bandai Namco Arts" },
    { value: "Avex Pictures", label: "Avex Pictures" },
    { value: "Sony Music Entertainment", label: "Sony Music Entertainment" },
    { value: "Toho", label: "Toho" },
    { value: "Fuji TV", label: "Fuji TV" },
    { value: "TV Tokyo", label: "TV Tokyo" },
    { value: "TBS", label: "TBS" },
    { value: "Nippon Animation", label: "Nippon Animation" },
    { value: "Pony Canyon", label: "Pony Canyon" },
    { value: "Wintakorn", label: "Reinako" },
]

export const licensors = [
    { value: "Crunchyroll", label: "Crunchyroll" },
    { value: "Funimation", label: "Funimation" },
    { value: "Sentai Filmworks", label: "Sentai Filmworks" },
    { value: "Aniplex of America", label: "Aniplex of America" },
    { value: "Viz Media", label: "Viz Media" },
    { value: "Discotek Media", label: "Discotek Media" },
    { value: "Netflix", label: "Netflix" },
    { value: "Amazon Prime Video", label: "Amazon Prime Video" },
    { value: "HIDIVE", label: "HIDIVE" },
]

export const studios = [
    { value: "Madhouse", label: "Madhouse" },
    { value: "Studio Pierrot", label: "Studio Pierrot" },
    { value: "Toei Animation", label: "Toei Animation" },
    { value: "Studio Ghibli", label: "Studio Ghibli" },
    { value: "Kyoto Animation", label: "Kyoto Animation" },
    { value: "Sunrise", label: "Sunrise" },
    { value: "Bones", label: "Bones" },
    { value: "A-1 Pictures", label: "A-1 Pictures" },
    { value: "Production I.G", label: "Production I.G" },
    { value: "MAPPA", label: "MAPPA" },
    { value: "CloverWorks", label: "CloverWorks" },
    { value: "ufotable", label: "ufotable" },
    { value: "Shaft", label: "Shaft" },
    { value: "J.C. Staff", label: "J.C. Staff" },
    { value: "White Fox", label: "White Fox" },
    { value: "Doga Kobo", label: "Doga Kobo" },
    { value: "Silver Link", label: "Silver Link" },
    { value: "Lerche", label: "Lerche" },
    { value: "Trigger", label: "Trigger" },
    { value: "TMS Entertainment", label: "TMS Entertainment" },
]